using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Text.Json;
using System.Text.Json.Serialization;
using Increase.Api.Core;
using Increase.Api.Exceptions;
using System = System;

namespace Increase.Api.Models.Files;

/// <summary>
/// Files are objects that represent a file hosted on Increase's servers. The file
/// may have been uploaded by you (for example, when uploading a check image) or it
/// may have been created by Increase (for example, an autogenerated statement PDF).
/// If you need to download a File, create a File Link.
/// </summary>
[JsonConverter(typeof(JsonModelConverter<File, FileFromRaw>))]
public sealed record class File : JsonModel
{
    /// <summary>
    /// The File's identifier.
    /// </summary>
    public required string ID
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("id");
        }
        init { this._rawData.Set("id", value); }
    }

    /// <summary>
    /// The time the File was created.
    /// </summary>
    public required System::DateTimeOffset CreatedAt
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullStruct<System::DateTimeOffset>("created_at");
        }
        init { this._rawData.Set("created_at", value); }
    }

    /// <summary>
    /// A description of the File.
    /// </summary>
    public required string? Description
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("description");
        }
        init { this._rawData.Set("description", value); }
    }

    /// <summary>
    /// Whether the File was generated by Increase or by you and sent to Increase.
    /// </summary>
    public required ApiEnum<string, Direction> Direction
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, Direction>>("direction");
        }
        init { this._rawData.Set("direction", value); }
    }

    /// <summary>
    /// The filename that was provided upon upload or generated by Increase.
    /// </summary>
    public required string? Filename
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("filename");
        }
        init { this._rawData.Set("filename", value); }
    }

    /// <summary>
    /// The idempotency key you chose for this object. This value is unique across
    /// Increase and is used to ensure that a request is only processed once. Learn
    /// more about [idempotency](https://increase.com/documentation/idempotency-keys).
    /// </summary>
    public required string? IdempotencyKey
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNullableClass<string>("idempotency_key");
        }
        init { this._rawData.Set("idempotency_key", value); }
    }

    /// <summary>
    /// The MIME type of the file.
    /// </summary>
    public required string MimeType
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<string>("mime_type");
        }
        init { this._rawData.Set("mime_type", value); }
    }

    /// <summary>
    /// What the File will be used for. We may add additional possible values for
    /// this enum over time; your application should be able to handle such additions gracefully.
    /// </summary>
    public required ApiEnum<string, FilePurpose> Purpose
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<ApiEnum<string, FilePurpose>>("purpose");
        }
        init { this._rawData.Set("purpose", value); }
    }

    /// <summary>
    /// A constant representing the object's type. For this resource it will always
    /// be `file`.
    /// </summary>
    public required ApiEnum<string, global::Increase.Api.Models.Files.Type> Type
    {
        get
        {
            this._rawData.Freeze();
            return this._rawData.GetNotNullClass<
                ApiEnum<string, global::Increase.Api.Models.Files.Type>
            >("type");
        }
        init { this._rawData.Set("type", value); }
    }

    /// <inheritdoc/>
    public override void Validate()
    {
        _ = this.ID;
        _ = this.CreatedAt;
        _ = this.Description;
        this.Direction.Validate();
        _ = this.Filename;
        _ = this.IdempotencyKey;
        _ = this.MimeType;
        this.Purpose.Validate();
        this.Type.Validate();
    }

    public File() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public File(File file)
        : base(file) { }
#pragma warning restore CS8618

    public File(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    File(FrozenDictionary<string, JsonElement> rawData)
    {
        this._rawData = new(rawData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="FileFromRaw.FromRawUnchecked"/>
    public static File FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData)
    {
        return new(FrozenDictionary.ToFrozenDictionary(rawData));
    }
}

class FileFromRaw : IFromRawJson<File>
{
    /// <inheritdoc/>
    public File FromRawUnchecked(IReadOnlyDictionary<string, JsonElement> rawData) =>
        File.FromRawUnchecked(rawData);
}

/// <summary>
/// Whether the File was generated by Increase or by you and sent to Increase.
/// </summary>
[JsonConverter(typeof(DirectionConverter))]
public enum Direction
{
    /// <summary>
    /// This File was sent by you to Increase.
    /// </summary>
    ToIncrease,

    /// <summary>
    /// This File was generated by Increase.
    /// </summary>
    FromIncrease,
}

sealed class DirectionConverter : JsonConverter<Direction>
{
    public override Direction Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "to_increase" => Direction.ToIncrease,
            "from_increase" => Direction.FromIncrease,
            _ => (Direction)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        Direction value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                Direction.ToIncrease => "to_increase",
                Direction.FromIncrease => "from_increase",
                _ => throw new IncreaseInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// What the File will be used for. We may add additional possible values for this
/// enum over time; your application should be able to handle such additions gracefully.
/// </summary>
[JsonConverter(typeof(FilePurposeConverter))]
public enum FilePurpose
{
    /// <summary>
    /// A file to be attached to a Card Dispute.
    /// </summary>
    CardDisputeAttachment,

    /// <summary>
    /// An image of the front of a check, used for check deposits.
    /// </summary>
    CheckImageFront,

    /// <summary>
    /// An image of the back of a check, used for check deposits.
    /// </summary>
    CheckImageBack,

    /// <summary>
    /// An image of the front of a deposited check after processing by Increase and
    /// submission to the Federal Reserve.
    /// </summary>
    ProcessedCheckImageFront,

    /// <summary>
    /// An image of the back of a deposited check after processing by Increase and
    /// submission to the Federal Reserve.
    /// </summary>
    ProcessedCheckImageBack,

    /// <summary>
    /// An image of a check that was mailed to a recipient.
    /// </summary>
    MailedCheckImage,

    /// <summary>
    /// A document to be printed on an additional page and mailed with a check that
    /// you've requested Increase print. This must be a PDF whose pages are all US
    /// letter size and all have the same orientation.
    /// </summary>
    CheckAttachment,

    /// <summary>
    /// An image to be used as the check voucher image, which is printed in the middle
    /// of the trifold area of a check. This must be a 2550x1100 pixel PNG.
    /// </summary>
    CheckVoucherImage,

    /// <summary>
    /// A signature image to be printed on a check. This must be a 1320x120 pixel PNG.
    /// </summary>
    CheckSignature,

    /// <summary>
    /// A scanned mail item sent to Increase.
    /// </summary>
    InboundMailItem,

    /// <summary>
    /// IRS Form 1099-INT.
    /// </summary>
    Form1099Int,

    /// <summary>
    /// IRS Form 1099-MISC.
    /// </summary>
    Form1099Misc,

    /// <summary>
    /// IRS Form SS-4.
    /// </summary>
    FormSS4,

    /// <summary>
    /// An image of a government-issued ID.
    /// </summary>
    IdentityDocument,

    /// <summary>
    /// A statement generated by Increase.
    /// </summary>
    IncreaseStatement,

    /// <summary>
    /// A supplemental document for a Loan Application.
    /// </summary>
    LoanApplicationSupplementalDocument,

    /// <summary>
    /// A file purpose not covered by any of the other cases.
    /// </summary>
    Other,

    /// <summary>
    /// A legal document forming a trust.
    /// </summary>
    TrustFormationDocument,

    /// <summary>
    /// A card image to be rendered inside digital wallet apps. This must be a 1536x969
    /// pixel PNG.
    /// </summary>
    DigitalWalletArtwork,

    /// <summary>
    /// An icon for you app to be rendered inside digital wallet apps. This must
    /// be a 100x100 pixel PNG.
    /// </summary>
    DigitalWalletAppIcon,

    /// <summary>
    /// A card image to be printed on the front of a physical card. This must be
    /// a 2100x1344 pixel PNG with no other color but black.
    /// </summary>
    PhysicalCardFront,

    /// <summary>
    /// The image to be printed on the back of a physical card.
    /// </summary>
    PhysicalCardBack,

    /// <summary>
    /// An image representing the entirety of the carrier used for a physical card.
    /// This must be a 2550x3300 pixel PNG with no other color but black.
    /// </summary>
    PhysicalCardCarrier,

    /// <summary>
    /// A document requested by Increase.
    /// </summary>
    DocumentRequest,

    /// <summary>
    /// A supplemental document associated an an Entity.
    /// </summary>
    EntitySupplementalDocument,

    /// <summary>
    /// The results of an Export you requested via the dashboard or API.
    /// </summary>
    Export,

    /// <summary>
    /// A fee statement.
    /// </summary>
    FeeStatement,

    /// <summary>
    /// An attachment to an Unusual Activity Report.
    /// </summary>
    UnusualActivityReportAttachment,

    /// <summary>
    /// A document granting another entity access to the funds into your account.
    /// </summary>
    DepositAccountControlAgreement,

    /// <summary>
    /// A file containing additional evidence for a Proof of Authorization Request Submission.
    /// </summary>
    ProofOfAuthorizationRequestSubmission,

    /// <summary>
    /// An account verification letter.
    /// </summary>
    AccountVerificationLetter,

    /// <summary>
    /// Funding instructions.
    /// </summary>
    FundingInstructions,

    /// <summary>
    /// A Hold Harmless Letter.
    /// </summary>
    HoldHarmlessLetter,
}

sealed class FilePurposeConverter : JsonConverter<FilePurpose>
{
    public override FilePurpose Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "card_dispute_attachment" => FilePurpose.CardDisputeAttachment,
            "check_image_front" => FilePurpose.CheckImageFront,
            "check_image_back" => FilePurpose.CheckImageBack,
            "processed_check_image_front" => FilePurpose.ProcessedCheckImageFront,
            "processed_check_image_back" => FilePurpose.ProcessedCheckImageBack,
            "mailed_check_image" => FilePurpose.MailedCheckImage,
            "check_attachment" => FilePurpose.CheckAttachment,
            "check_voucher_image" => FilePurpose.CheckVoucherImage,
            "check_signature" => FilePurpose.CheckSignature,
            "inbound_mail_item" => FilePurpose.InboundMailItem,
            "form_1099_int" => FilePurpose.Form1099Int,
            "form_1099_misc" => FilePurpose.Form1099Misc,
            "form_ss_4" => FilePurpose.FormSS4,
            "identity_document" => FilePurpose.IdentityDocument,
            "increase_statement" => FilePurpose.IncreaseStatement,
            "loan_application_supplemental_document" =>
                FilePurpose.LoanApplicationSupplementalDocument,
            "other" => FilePurpose.Other,
            "trust_formation_document" => FilePurpose.TrustFormationDocument,
            "digital_wallet_artwork" => FilePurpose.DigitalWalletArtwork,
            "digital_wallet_app_icon" => FilePurpose.DigitalWalletAppIcon,
            "physical_card_front" => FilePurpose.PhysicalCardFront,
            "physical_card_back" => FilePurpose.PhysicalCardBack,
            "physical_card_carrier" => FilePurpose.PhysicalCardCarrier,
            "document_request" => FilePurpose.DocumentRequest,
            "entity_supplemental_document" => FilePurpose.EntitySupplementalDocument,
            "export" => FilePurpose.Export,
            "fee_statement" => FilePurpose.FeeStatement,
            "unusual_activity_report_attachment" => FilePurpose.UnusualActivityReportAttachment,
            "deposit_account_control_agreement" => FilePurpose.DepositAccountControlAgreement,
            "proof_of_authorization_request_submission" =>
                FilePurpose.ProofOfAuthorizationRequestSubmission,
            "account_verification_letter" => FilePurpose.AccountVerificationLetter,
            "funding_instructions" => FilePurpose.FundingInstructions,
            "hold_harmless_letter" => FilePurpose.HoldHarmlessLetter,
            _ => (FilePurpose)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        FilePurpose value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                FilePurpose.CardDisputeAttachment => "card_dispute_attachment",
                FilePurpose.CheckImageFront => "check_image_front",
                FilePurpose.CheckImageBack => "check_image_back",
                FilePurpose.ProcessedCheckImageFront => "processed_check_image_front",
                FilePurpose.ProcessedCheckImageBack => "processed_check_image_back",
                FilePurpose.MailedCheckImage => "mailed_check_image",
                FilePurpose.CheckAttachment => "check_attachment",
                FilePurpose.CheckVoucherImage => "check_voucher_image",
                FilePurpose.CheckSignature => "check_signature",
                FilePurpose.InboundMailItem => "inbound_mail_item",
                FilePurpose.Form1099Int => "form_1099_int",
                FilePurpose.Form1099Misc => "form_1099_misc",
                FilePurpose.FormSS4 => "form_ss_4",
                FilePurpose.IdentityDocument => "identity_document",
                FilePurpose.IncreaseStatement => "increase_statement",
                FilePurpose.LoanApplicationSupplementalDocument =>
                    "loan_application_supplemental_document",
                FilePurpose.Other => "other",
                FilePurpose.TrustFormationDocument => "trust_formation_document",
                FilePurpose.DigitalWalletArtwork => "digital_wallet_artwork",
                FilePurpose.DigitalWalletAppIcon => "digital_wallet_app_icon",
                FilePurpose.PhysicalCardFront => "physical_card_front",
                FilePurpose.PhysicalCardBack => "physical_card_back",
                FilePurpose.PhysicalCardCarrier => "physical_card_carrier",
                FilePurpose.DocumentRequest => "document_request",
                FilePurpose.EntitySupplementalDocument => "entity_supplemental_document",
                FilePurpose.Export => "export",
                FilePurpose.FeeStatement => "fee_statement",
                FilePurpose.UnusualActivityReportAttachment => "unusual_activity_report_attachment",
                FilePurpose.DepositAccountControlAgreement => "deposit_account_control_agreement",
                FilePurpose.ProofOfAuthorizationRequestSubmission =>
                    "proof_of_authorization_request_submission",
                FilePurpose.AccountVerificationLetter => "account_verification_letter",
                FilePurpose.FundingInstructions => "funding_instructions",
                FilePurpose.HoldHarmlessLetter => "hold_harmless_letter",
                _ => throw new IncreaseInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}

/// <summary>
/// A constant representing the object's type. For this resource it will always be `file`.
/// </summary>
[JsonConverter(typeof(TypeConverter))]
public enum Type
{
    File,
}

sealed class TypeConverter : JsonConverter<global::Increase.Api.Models.Files.Type>
{
    public override global::Increase.Api.Models.Files.Type Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "file" => global::Increase.Api.Models.Files.Type.File,
            _ => (global::Increase.Api.Models.Files.Type)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        global::Increase.Api.Models.Files.Type value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                global::Increase.Api.Models.Files.Type.File => "file",
                _ => throw new IncreaseInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
