using System.Collections.Frozen;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Net.Http;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using Increase.Api.Core;
using Increase.Api.Exceptions;
using System = System;

namespace Increase.Api.Models.OAuthTokens;

/// <summary>
/// Create an OAuth Token
///
/// <para>NOTE: Do not inherit from this type outside the SDK unless you're okay with
/// breaking changes in non-major versions. We may add new methods in the future that
/// cause existing derived classes to break.</para>
/// </summary>
public record class OAuthTokenCreateParams : ParamsBase
{
    readonly JsonDictionary _rawBodyData = new();
    public IReadOnlyDictionary<string, JsonElement> RawBodyData
    {
        get { return this._rawBodyData.Freeze(); }
    }

    /// <summary>
    /// The credential you request in exchange for the code. In Production, this
    /// is always `authorization_code`. In Sandbox, you can pass either enum value.
    /// </summary>
    public required ApiEnum<string, GrantType> GrantType
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNotNullClass<ApiEnum<string, GrantType>>("grant_type");
        }
        init { this._rawBodyData.Set("grant_type", value); }
    }

    /// <summary>
    /// The public identifier for your application.
    /// </summary>
    public string? ClientID
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("client_id");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawBodyData.Set("client_id", value);
        }
    }

    /// <summary>
    /// The secret that confirms you own the application. This is redundant given
    /// that the request is made with your API key but it's a required component
    /// of OAuth 2.0.
    /// </summary>
    public string? ClientSecret
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("client_secret");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawBodyData.Set("client_secret", value);
        }
    }

    /// <summary>
    /// The authorization code generated by the user and given to you as a query parameter.
    /// </summary>
    public string? Code
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("code");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawBodyData.Set("code", value);
        }
    }

    /// <summary>
    /// The production token you want to exchange for a sandbox token. This is only
    /// available in Sandbox. Set `grant_type` to `production_token` to use this parameter.
    /// </summary>
    public string? ProductionToken
    {
        get
        {
            this._rawBodyData.Freeze();
            return this._rawBodyData.GetNullableClass<string>("production_token");
        }
        init
        {
            if (value == null)
            {
                return;
            }

            this._rawBodyData.Set("production_token", value);
        }
    }

    public OAuthTokenCreateParams() { }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    public OAuthTokenCreateParams(OAuthTokenCreateParams oauthTokenCreateParams)
        : base(oauthTokenCreateParams)
    {
        this._rawBodyData = new(oauthTokenCreateParams._rawBodyData);
    }
#pragma warning restore CS8618

    public OAuthTokenCreateParams(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }

#pragma warning disable CS8618
    [SetsRequiredMembers]
    OAuthTokenCreateParams(
        FrozenDictionary<string, JsonElement> rawHeaderData,
        FrozenDictionary<string, JsonElement> rawQueryData,
        FrozenDictionary<string, JsonElement> rawBodyData
    )
    {
        this._rawHeaderData = new(rawHeaderData);
        this._rawQueryData = new(rawQueryData);
        this._rawBodyData = new(rawBodyData);
    }
#pragma warning restore CS8618

    /// <inheritdoc cref="IFromRawJson{T}.FromRawUnchecked"/>
    public static OAuthTokenCreateParams FromRawUnchecked(
        IReadOnlyDictionary<string, JsonElement> rawHeaderData,
        IReadOnlyDictionary<string, JsonElement> rawQueryData,
        IReadOnlyDictionary<string, JsonElement> rawBodyData
    )
    {
        return new(
            FrozenDictionary.ToFrozenDictionary(rawHeaderData),
            FrozenDictionary.ToFrozenDictionary(rawQueryData),
            FrozenDictionary.ToFrozenDictionary(rawBodyData)
        );
    }

    public override string ToString() =>
        JsonSerializer.Serialize(
            FriendlyJsonPrinter.PrintValue(
                new Dictionary<string, JsonElement>()
                {
                    ["HeaderData"] = FriendlyJsonPrinter.PrintValue(
                        JsonSerializer.SerializeToElement(this._rawHeaderData.Freeze())
                    ),
                    ["QueryData"] = FriendlyJsonPrinter.PrintValue(
                        JsonSerializer.SerializeToElement(this._rawQueryData.Freeze())
                    ),
                    ["BodyData"] = FriendlyJsonPrinter.PrintValue(this._rawBodyData.Freeze()),
                }
            ),
            ModelBase.ToStringSerializerOptions
        );

    public virtual bool Equals(OAuthTokenCreateParams? other)
    {
        if (other == null)
        {
            return false;
        }
        return this._rawHeaderData.Equals(other._rawHeaderData)
            && this._rawQueryData.Equals(other._rawQueryData)
            && this._rawBodyData.Equals(other._rawBodyData);
    }

    public override System::Uri Url(ClientOptions options)
    {
        return new System::UriBuilder(options.BaseUrl.ToString().TrimEnd('/') + "/oauth/tokens")
        {
            Query = this.QueryString(options),
        }.Uri;
    }

    internal override HttpContent? BodyContent()
    {
        return new StringContent(
            JsonSerializer.Serialize(this.RawBodyData, ModelBase.SerializerOptions),
            Encoding.UTF8,
            "application/json"
        );
    }

    internal override void AddHeadersToRequest(HttpRequestMessage request, ClientOptions options)
    {
        ParamsBase.AddDefaultHeaders(request, options);
        foreach (var item in this.RawHeaderData)
        {
            ParamsBase.AddHeaderElementToRequest(request, item.Key, item.Value);
        }
    }

    public override int GetHashCode()
    {
        return 0;
    }
}

/// <summary>
/// The credential you request in exchange for the code. In Production, this is always
/// `authorization_code`. In Sandbox, you can pass either enum value.
/// </summary>
[JsonConverter(typeof(GrantTypeConverter))]
public enum GrantType
{
    /// <summary>
    /// An OAuth authorization code.
    /// </summary>
    AuthorizationCode,

    /// <summary>
    /// An OAuth production token.
    /// </summary>
    ProductionToken,
}

sealed class GrantTypeConverter : JsonConverter<GrantType>
{
    public override GrantType Read(
        ref Utf8JsonReader reader,
        System::Type typeToConvert,
        JsonSerializerOptions options
    )
    {
        return JsonSerializer.Deserialize<string>(ref reader, options) switch
        {
            "authorization_code" => GrantType.AuthorizationCode,
            "production_token" => GrantType.ProductionToken,
            _ => (GrantType)(-1),
        };
    }

    public override void Write(
        Utf8JsonWriter writer,
        GrantType value,
        JsonSerializerOptions options
    )
    {
        JsonSerializer.Serialize(
            writer,
            value switch
            {
                GrantType.AuthorizationCode => "authorization_code",
                GrantType.ProductionToken => "production_token",
                _ => throw new IncreaseInvalidDataException(
                    string.Format("Invalid value '{0}' in {1}", value, nameof(value))
                ),
            },
            options
        );
    }
}
