# This workflow is triggered when a GitHub release is created.
# It can also be run manually to re-publish to NuGet in case it failed for some reason.
# You can run this workflow by navigating to https://www.github.com/Increase/increase-csharp/actions/workflows/publish-nuget.yml
name: Publish NuGet
on:
  workflow_dispatch:

  release:
    types: [published]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: "8.0.x"

      - name: Pack
        run: dotnet pack src/Increase.Api/Increase.Api.csproj --configuration Release --output ./artifacts

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@8d196754b4036150537f80ac539e15c2f1028841 # v1.2.0
        id: login
        with:
          user: ${{ vars.NUGET_USER }}

      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
